#!/usr/bin/perl -w

use strict;
use List::Util 'shuffle';

my ($maxchan, $sleeptime, @chans, $iface) = (11,1);

$iface = $ARGV[0] || 'mon0';

do {
  print("Hopping on $iface channels 1-$maxchan  dwelling ${sleeptime}s. ");
  fork and exit;
};

print("forked to pid $$\n\n");
#open('>/tmp/chop.pid');
#print "Device $iface: Hopping across $maxchan channels, sleeping for $sleeptime seconds.\n\n";

do {
  @chans = (1..$maxchan);
  foreach(shuffle(@chans)) {
    system("iw dev $iface set channel $_");
    sleep($sleeptime);
  }
} while 1
