#!/usr/bin/python
''' usage: $0 [mac address] [...] - resolve mac address vendors '''

import sys
from netaddr import *

if len(sys.argv) < 2:
  print __doc__
  sys.exit(-1)

for mac in sys.argv[1:]:
  try: vendor = EUI(mac).oui.registration().org
  except: vendor = 'Unknown'
  print '"%s","%s"' % (mac, vendor)
